### ISSUE TITLE
GH Actions automatic PyPI builds are failing

### ISSUE THREAD

**Issue by ischoegl** [Cantera/pypi-packages#1]
While there were a couple of recent successful runs, the build process started failing again, e.g. https://github.com/Cantera/pypi-packages/actions/runs/4522070749

**Comment by bryanwweber** [comment]
Thanks for noting this @ischoegl. I started looking into it in #991 but decided it's going to take a bit more work to get it going. I'll look at this ASAP.

**Comment by bryanwweber** [comment]
Fixed by #2 and Cantera/cantera#1484
