### ISSUE TITLE
Link SUNDIALS with a BLAS & LAPACK implementation

### ISSUE THREAD

**Issue by bryanwweber** [Cantera/pypi-packages#6]
This should be fairly easy to do on Linux by updating the manylinux image. Likewise on macOS, we can likely compile something at build time (compile something because otherwise we might end up with mismatched `MACOSX_TARGET_VERSION` from a brew-installed version). Windows might be a little tougher.

**Comment by speth** [comment]
For Linux, where would the BLAS/LAPACK library come from at runtime? I guess this would require bundling the BLAS/LAPACK shared libraries with Cantera or explicitly linking to a static version of BLAS/LAPACK? Or perhaps piggybacking off of whatever library Numpy bundles, assuming contains all the functions we need.

For macOS, I think the easiest and best option is to just link to the Accelerate framework.

**Comment by bryanwweber** [comment]
> where would the BLAS/LAPACK library come from at runtime

Wheels are always "repaired" so that links are rewritten to a bundled, uniquely named, copy of non-libc and non-libpython dependencies. This is how we're already including libhdf, libfmt, etc.

> Accelerate

Yep, that was also my conclusion 👍

**Comment by speth** [comment]
Ah, I see. Glad to know that this bundling step is an existing feature.

**Comment by bryanwweber** [comment]
Closed by #9! 🎉
